name: "Vulnmap Ruby"
description: "Check your Ruby application for vulnerabilties using Vulnmap"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Vulnmap command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Vulnmap"
  json:
    description: "Output a vulnmap.json file with results if running the test command"
    default: false
runs:
  using: "docker"
  image: "docker://khulnasoft/vulnmap:ruby"
  env:
    FORCE_COLOR: 2
    VULNMAP_INTEGRATION_NAME: GITHUB_ACTIONS
    VULNMAP_INTEGRATION_VERSION: ruby
  args:
  - vulnmap
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
